# Generated by Django 4.2.8 on 2026-01-14 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('difficulty_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность (1-5)')),
                ('playtime', models.PositiveIntegerField(help_text='В минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Среднее время партии (мин)')),
                ('min_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальное количество игроков')),
                ('max_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество игроков')),
                ('letsplays', models.TextField(blank=True, help_text='Ссылки на YouTube или другие видео, разделенные запятой', verbose_name='Ссылки на летсплеи (через запятую)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game')),
            ],
            options={
                'verbose_name': 'Фотография игры',
                'verbose_name_plural': 'Фотографии игр',
                'ordering': ['order'],
            },
        ),
    ]
