# Generated by Django 6.0 on 2026-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('min_players', models.IntegerField(verbose_name='Игроков от')),
                ('max_players', models.IntegerField(verbose_name='Игроков до')),
                ('playtime', models.CharField(max_length=50, verbose_name='Время игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rules_link', models.URLField(blank=True, verbose_name='Ссылка на правила')),
                ('video_link', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('complexity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Сложность')),
            ],
        ),
    ]
