# Generated by Django 6.0 on 2026-01-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='complexity',
            field=models.IntegerField(verbose_name='Сложность'),
        ),
    ]
