# Generated by Django 6.0 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_complexity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='complexity',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(default=3, verbose_name='Сложность'),
        ),
    ]
