# Generated by Django 6.0 on 2026-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options_game_main_image_gameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playtime_minutes',
            field=models.IntegerField(default=60, verbose_name='Время в минутах'),
        ),
    ]
