# Generated by Django 6.0 on 2026-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_category_game_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gameimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Изображение игры', 'verbose_name_plural': 'Изображения игр'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='game',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='playtime',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='gameimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='gameimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(help_text='Класс FontAwesome (например, fa-gamepad)', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.FloatField(blank=True, null=True, verbose_name='Сложность (1-5)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(default=2, verbose_name='Минимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playtime_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время игры (минуты)'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='game_images/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
