# Generated by Django 6.0 on 2026-01-07 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_options_alter_gameimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gameimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='gameimage',
            name='order',
        ),
        migrations.AddField(
            model_name='gameimage',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(verbose_name='Максимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(verbose_name='Минимальное количество игроков'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playtime_minutes',
            field=models.IntegerField(verbose_name='Время игры (минуты)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.CharField(blank=True, max_length=200, verbose_name='Категории'),
        ),
    ]
